"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Info, ShieldCheck } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

interface ToggleConfig {
  key: string;
  label: string;
  description: string;
  defaultChecked: boolean;
}

const TOGGLES: ToggleConfig[] = [
  {
    key: "autoGenerateDrafts",
    label: "Auto-generate content drafts",
    description:
      "Let AI create first-draft briefs and articles for approved topics. Drafts still wait for a writer to review before anything ships.",
    defaultChecked: true,
  },
  {
    key: "autoApplyMetaFixes",
    label: "Auto-apply meta tag fixes",
    description: "Let AI push low-risk title and meta description fixes straight to a website, without a manual review step.",
    defaultChecked: false,
  },
  {
    key: "slackRecommendations",
    label: "Send AI recommendations to Slack",
    description: "Post new AI-generated recommendations to your connected Slack channel as soon as they're ready.",
    defaultChecked: true,
  },
];

const TONE_OPTIONS = [
  { value: "conversational", label: "Conversational" },
  { value: "professional", label: "Professional" },
  { value: "technical", label: "Technical" },
] as const;

export function AiSettingsPanel() {
  const [toggles, setToggles] = useState<Record<string, boolean>>(() =>
    Object.fromEntries(TOGGLES.map((toggle) => [toggle.key, toggle.defaultChecked])),
  );
  const [autoPublish, setAutoPublish] = useState(false);
  const [tone, setTone] = useState<string>("professional");

  function handleToggle(toggle: ToggleConfig, checked: boolean) {
    setToggles((prev) => ({ ...prev, [toggle.key]: checked }));
    toast.success(`${toggle.label} ${checked ? "enabled" : "disabled"}.`);
  }

  return (
    <div className="mx-auto max-w-2xl space-y-4">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ShieldCheck className="size-4 text-primary" /> AI recommends, your team approves
          </CardTitle>
          <CardDescription>
            Control exactly where AI is allowed to act on its own, and where it should always wait for a human to sign off.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {TOGGLES.map((toggle) => (
            <div key={toggle.key} className="flex items-center justify-between gap-4 rounded-lg border p-3.5">
              <div className="min-w-0 space-y-0.5">
                <Label htmlFor={toggle.key} className="text-sm font-medium">
                  {toggle.label}
                </Label>
                <p className="text-xs text-muted-foreground">{toggle.description}</p>
              </div>
              <Switch
                id={toggle.key}
                checked={toggles[toggle.key]}
                onCheckedChange={(checked) => handleToggle(toggle, checked)}
              />
            </div>
          ))}

          <Tooltip>
            <TooltipTrigger
              render={
                <div className="flex items-center justify-between gap-4 rounded-lg border border-dashed p-3.5 opacity-70">
                  <div className="min-w-0 space-y-0.5">
                    <Label htmlFor="autoPublish" className="flex items-center gap-1.5 text-sm font-medium">
                      Auto-publish AI content <Info className="size-3.5 text-muted-foreground" />
                    </Label>
                    <p className="text-xs text-muted-foreground">
                      Publish AI-written content live without a review step. Disabled by design.
                    </p>
                  </div>
                  <Switch
                    id="autoPublish"
                    checked={autoPublish}
                    onCheckedChange={(checked) => setAutoPublish(checked)}
                    disabled
                  />
                </div>
              }
            />
            <TooltipContent>Human review is always required before AI content goes live.</TooltipContent>
          </Tooltip>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Content voice</CardTitle>
          <CardDescription>The tone AI should use when drafting content, briefs and recommendations.</CardDescription>
        </CardHeader>
        <CardContent>
          <Select
            value={tone}
            onValueChange={(value) => {
              if (!value) return;
              setTone(value);
              const label = TONE_OPTIONS.find((option) => option.value === value)?.label ?? value;
              toast.success(`AI writing tone set to ${label}.`);
            }}
          >
            <SelectTrigger className="w-full sm:w-64">
              <SelectValue placeholder="Select a tone">
                {(value: string | null) => TONE_OPTIONS.find((option) => option.value === value)?.label ?? "Select a tone"}
              </SelectValue>
            </SelectTrigger>
            <SelectContent>
              {TONE_OPTIONS.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </CardContent>
      </Card>
    </div>
  );
}
